#!/usr/bin/env python3
"""Build the starter catalog. Existing product photos are referenced as-is."""
import json
from pathlib import Path

CAT = {
    "clothing": "Clothings for men and women",
    "household": "Household items",
    "ankara": "Ankara ready to wear",
    "accessories": "Accessories",
    "beauty": "Beauty",
    "shoes": "Shoes",
    "gadgets": "Gadgets / Electronics",
    "packaging": "Packaging",
    "skincare": "Skincare",
    "bags": "Bags",
    "hair-care": "Hair care",
    "nails": "Nails",
    "gift-set": "Gift set",
    "children": "Children items",
    "decor": "Decor",
}

# Category cover images already in the project — never rewritten
IMG = {
    "clothing": "images/categories/fashion.jpg",
    "household": "images/categories/household.jpg",
    "ankara": "images/categories/fashion.jpg",
    "accessories": "images/categories/gadgets.jpg",
    "beauty": "images/categories/beauty.jpg",
    "shoes": "images/categories/shoes.jpg",
    "gadgets": "images/categories/gadgets.jpg",
    "packaging": "images/categories/household.jpg",
    "skincare": "images/categories/beauty.jpg",
    "bags": "images/categories/bags.jpg",
    "hair-care": "images/categories/beauty.jpg",
    "nails": "images/categories/beauty.jpg",
    "gift-set": "images/categories/household.jpg",
    "children": "images/categories/fashion.jpg",
    "decor": "images/categories/household.jpg",
}

def P(i, name, cat, cfa, ngn, image, compare_cfa=None, compare_ngn=None,
      stock=24, badge="", featured=False, colors=None, desc=""):
    slug = (
        name.lower()
        .replace("&", "and")
        .replace("/", " ")
        .replace("'", "")
    )
    for ch in ".,()":
        slug = slug.replace(ch, "")
    slug = "-".join(slug.split())
    if not desc:
        desc = (
            f"Curated by J Aura Store. Premium {CAT[cat].lower()} — "
            f"{name}. Quality you can feel, priced for wholesale luxury."
        )
    return {
        "id": f"ja-{i:03d}",
        "sku": f"JA{i:03d}",
        "slug": slug,
        "name": name,
        "category": cat,
        "priceCfa": cfa,
        "compareCfa": compare_cfa,
        "priceNgn": ngn,
        "compareNgn": compare_ngn,
        "image": image,
        "description": desc,
        "stock": stock,
        "badge": badge,
        "featured": featured,
        "colors": colors or [],
    }

products = []
n = 1

# --- Real products from the original J Aura Store (original photos, untouched) ---
real = [
    ("Mouth Spray", "beauty", 600, 1400, "images/products/mouth-spray.jpg", 1000, None, 40, "sale", True, [],
     "Fresh-breath mouth spray. Compact, travel-ready, and a daily essential."),
    ("Bag K", "bags", 3200, 7500, "images/products/bag-k.jpg", None, None, 18, "", True, [],
     "Structured everyday bag with a refined finish. Spacious and elegant."),
    ("Mini Fan", "household", 1600, 3850, "images/products/mini-fan.jpg", 3000, None, 30, "sale", True, [],
     "Portable mini fan for home, office, and travel. Quiet, compact cooling."),
    ("Key Holder", "accessories", 325, 750, "images/products/key-holder.jpg", None, None, 50, "", False, [],
     "Compact key holder. Keep keys organised with a clean, durable finish."),
    ("Q8 Wireless Microphone", "gadgets", 6500, 15700, "images/products/q8-mic.jpg", 15000, None, 12, "sale", True, [],
     "Q8 wireless microphone for content, church, and events. Clear pickup."),
    ("Electric Steam Iron", "household", 6800, 16000, "images/products/steam-iron.jpg", None, None, 16, "", True, [],
     "Electric steam iron for crisp, effortless pressing at home."),
    ("Enny Big Bag with Scarf", "bags", 9000, 22000, "images/products/enny-bag.jpg", None, None, 10, "bestseller", True, [],
     "Very big. Quality is great. Statement tote that arrives with a matching scarf."),
    ("2-in-1 Lipstick Lipgloss", "beauty", 1000, 2400, "images/products/lipstick.jpg", 1500, None, 35, "sale", True, [],
     "Colour and shine in one. A 2-in-1 lipstick and lipgloss for everyday glam."),
    ("Heels", "shoes", 11000, 27000, "images/products/heels.jpg", None, None, 8, "", True, [],
     "Elegant heels for occasions and evenings. Comfortable height, polished finish."),
    ("Min Min Bag", "bags", 4200, 10000, "images/products/minmin-bag.jpg", None, None, 14, "", True, [],
     "Compact Min Min bag. Lightweight, stylish, and easy to carry."),
    ("Luki 2-in-1 Bag", "bags", 8500, 20000, "images/products/luki-bag.jpg", None, None, 11, "", True, [],
     "Luki 2-in-1 bag. Two looks, one piece — day to evening versatility."),
    ("Selfie Stick", "gadgets", 2100, 5000, "images/products/selfie-stick.jpg", 3500, None, 22, "sale", False, [],
     "Extendable selfie stick for phones. Stable grip, easy pairing."),
    ("Leather Crocs Bag", "bags", 7800, 19000, "images/products/crocs-bag.jpg", 10000, None, 9, "sale", True, [],
     "Textured leather Crocs bag. Statement structure with a luxury feel."),
    ("Tomi Wrist Watch 02", "accessories", 9600, 23000, "images/products/tomi-watch.jpg", None, None, 10, "", True, [],
     "Tomi wrist watch 02. Clean dial, refined strap, everyday luxury."),
    ("Acne Removal Face Mask", "skincare", 250, 550, "images/products/acne-mask.jpg", 500, None, 60, "sale", False, [],
     "Targeted acne-removal face mask. Gentle cleanse for clearer-looking skin."),
    ("Vacuum Phone Holder", "gadgets", 2000, 4900, "images/products/vacuum-holder.jpg", 3500, None, 20, "sale", False, [],
     "Vacuum phone holder for dashboards and desks. Strong hold, easy release."),
    ("2 Layers Plate Rack", "household", 11500, 28000, "images/products/plate-rack.jpg", 14000, None, 8, "sale", False, [],
     "Two-layer plate rack. Dry, store, and display dinnerware neatly."),
    ("24 Pcs Gold Cutlery Set", "household", 7600, 18500, "images/products/gold-cutlery.jpg", 9500, None, 12, "sale", True, [],
     "24-piece gold cutlery set. Table-ready luxury for hosting."),
    ("Wipes 5 Packs", "household", 1100, 2500, "images/products/wipes.jpg", 2000, None, 40, "sale", False, [],
     "Five-pack wipes. Soft, reliable, everyday clean."),
    ("Electronic Personal Scale", "household", 3700, 9000, "images/products/scale.jpg", 5000, None, 0, "sale", False, [],
     "Digital personal scale. Precise reading, slim profile."),
    ("Kitchen Tissue", "household", 1250, 3000, "images/products/kitchen-tissue.jpg", 2800, None, 45, "sale", False, [],
     "Absorbent kitchen tissue roll. A restock essential."),
    ("Wrist BP Monitor", "gadgets", 5200, 12500, "images/products/bp-wrist.jpg", 7000, None, 10, "sale", False, [],
     "Wrist blood-pressure monitor. Compact health check at home."),
    ("AC Design Fan", "household", 5600, 13500, "images/products/ac-fan.jpg", None, None, 14, "new", True, [],
     "AC-design fan. Quiet airflow with a modern silhouette."),
    ("Shoe Wipes", "household", 680, 1600, "images/products/shoe-wipes.jpg", None, None, 40, "", False, [],
     "Quick shoe wipes. Restore shine on the go."),
    ("Stanley Cup", "household", 5400, 13000, "images/products/stanley.jpg", None, None, 16, "", True, [],
     "Insulated Stanley-style cup. Keeps drinks cold or hot for hours."),
    ("Menstrual Relief Belt", "beauty", 4900, 12000, "images/products/relief-belt.jpg", 6000, None, 15, "sale", False, [],
     "Warming menstrual relief belt. Soothing comfort when you need it."),
    ("3-in-1 Fancy Cup Set", "household", 3700, 9100, "images/products/fancy-cups.jpg", 4900, None, 18, "sale", False, [],
     "Three-piece fancy cup set. Gift-ready and table-pretty."),
    ("Underwear Hanger", "household", 2100, 5000, "images/products/hanger.jpg", 3500, None, 25, "sale", False, [],
     "Space-saving underwear hanger. Closet organisation made simple."),
    ("Mop", "household", 7200, 17500, "images/products/mop.jpg", 10000, None, 12, "sale", False, [],
     "Efficient mop for tiled and sealed floors. Easy wring, deep clean."),
    ("Inflatable Sofa with Leg Rest", "household", 11700, 28500, "images/products/sofa.jpg", None, None, 6, "", True, ["Light blue", "Wine"],
     "Inflatable sofa with leg rest. Lounge-ready comfort in two colours."),
    ("Hello Master Bottle", "household", 1000, 2450, "images/products/bottle.jpg", 1800, None, 28, "sale", False, ["Green", "Blue"],
     "Hello Master water bottle. Leak-resistant and everyday ready."),
    ("17 Pcs Sealed Crisper Plastics", "household", 5300, 13000, "images/products/crisper.jpg", 7000, None, 10, "sale", False, [],
     "17-piece sealed crisper set. Keep produce and leftovers fresher."),
    ("Marble Twin Center Table", "decor", 41000, 100000, "images/products/marble-twin.jpg", None, None, 3, "", True, [],
     "Marble twin center table. A statement pair for living rooms."),
    ("Marble Center Table", "decor", 35000, 85500, "images/products/marble-table.jpg", None, None, 4, "", True, [],
     "Marble center table. Sculptural luxury for modern interiors."),
    ("3 Layers Dish Washer", "household", 11900, 29000, "images/products/dishwasher.jpg", 15000, None, 7, "sale", False, [],
     "Three-layer dish rack / washer stand. Drain and store with ease."),
    ("12 Pcs Dessini Pot Set", "household", 34700, 85000, "images/products/dessini.jpg", None, None, 5, "", True, [],
     "12-piece Dessini pot set. Full cookware suite for serious kitchens."),
    ("7 Pcs Aluminum Pot", "household", 32000, 78500, "images/products/alum-pot.jpg", 50000, None, 6, "sale", True, [],
     "7-piece aluminum pot set. Even heat, everyday durability."),
    ("Clothes Pegs", "household", 600, 1470, "images/products/pegs.jpg", 1000, None, 50, "sale", False, [],
     "Sturdy clothes pegs. A laundry-day essential."),
    ("Portable Rechargeable Fan", "gadgets", 6000, 14700, "images/products/portable-fan.jpg", 8000, None, 14, "sale", False, [],
     "Portable rechargeable fan. Cordless breeze wherever you sit."),
    ("Toilet Fragrance", "household", 600, 1500, "images/products/toilet-frag.jpg", 900, None, 40, "sale", False, [],
     "Toilet fragrance. Fresh, lasting scent for bathrooms."),
    ("Mini Diffuser", "household", 950, 2300, "images/products/mini-diffuser.jpg", 1500, None, 22, "sale", False, [],
     "Mini diffuser. Soft fragrance for desks, cars, and small rooms."),
    ("Glow in the Dark", "decor", 800, 1960, "images/products/glow.jpg", 1200, None, 30, "sale", False, [],
     "Glow-in-the-dark décor piece. Playful light after sunset."),
    ("Car Diffuser", "household", 500, 1225, "images/products/car-diffuser.jpg", 950, None, 35, "sale", False, [],
     "Car diffuser. A clean scent for every drive."),
    ("M10 Earpod", "gadgets", 3900, 9500, "images/products/earpod.jpg", 5000, None, 18, "sale", True, [],
     "M10 earpods. Wireless listening with a compact charging case."),
    ("Fur Cap", "clothing", 1500, 3700, "images/products/fur-cap.jpg", 2000, None, 20, "sale", False, [],
     "Soft fur cap. Warm, stylish, and easy to pair."),
    ("6-in-1 Lipgloss Set", "beauty", 2000, 4900, "images/products/lipgloss-set.jpg", 3500, None, 20, "sale", True, [],
     "Six-shade lipgloss set. A full glam wardrobe in one kit."),
    ("Mini Mirror", "beauty", 400, 950, "images/products/mini-mirror.jpg", 800, None, 40, "sale", False, [],
     "Compact mini mirror. Purse-ready and crystal clear."),
    ("Hair Scrunchies 4-in-1", "hair-care", 1250, 3000, "images/products/scrunchies.jpg", 1800, None, 30, "bestseller", True, [],
     "Four-pack hair scrunchies. Soft hold, no harsh crease."),
    ("Beard Balm", "beauty", 1200, 2950, "images/products/beard-balm.jpg", 2000, None, 22, "sale", False, [],
     "Beard balm. Softens, shapes, and adds a healthy sheen."),
    ("Blue Idea Rechargeable Clipper", "beauty", 4800, 11750, "images/products/clipper.jpg", 6000, None, 10, "sale", False, [],
     "Rechargeable clipper. Precise cut, cordless convenience."),
    ("Lip Gel", "beauty", 450, 1150, "images/products/lip-gel.jpg", 600, None, 35, "sale", False, [],
     "Hydrating lip gel. Glossy comfort for dry lips."),
    ("Lip Scrub", "beauty", 1000, 2450, "images/products/lip-scrub.jpg", 1500, None, 28, "sale", False, [],
     "Lip scrub. Smooths before colour for a refined finish."),
    ("Q13 AI Smart Tracking Tripod", "gadgets", 16350, 40000, "images/products/tripod.jpg", 20000, None, 6, "new", True, [],
     "Q13 AI tracking tripod with light. Follows you while you create."),
    ("F15 Wireless Mic — Single", "gadgets", 5350, 13000, "images/products/f15-mic.jpg", 7500, None, 0, "sale", False, [],
     "F15 wireless microphone, single kit. Stage and content ready."),
    ("100L Storage Bag", "household", 4200, 10300, "images/products/storage-bag.jpg", 6000, None, 16, "sale", False, [],
     "100-litre storage bag. Fold-flat organisation for bulky items."),
]

for item in real:
    products.append(P(n, *item))
    n += 1

# Extra catalog so the store launches with 220+ listings.
# Photos reuse existing category / product images — files are never rewritten.
# Owners replace any photo from Admin → Products.

extras = [
    # Bags
    ("Aura Mini Crossbody", "bags", 3800, 9200, "images/products/minmin-bag.jpg", 4500, None, 14, "new", False, ["Black", "Tan"]),
    ("Structured Work Tote", "bags", 9800, 23800, "images/products/enny-bag.jpg", None, None, 8, "", False, ["Cream", "Black"]),
    ("Croc Mini Clutch", "bags", 5400, 13200, "images/products/crocs-bag.jpg", 6200, None, 12, "sale", False, ["Wine", "Gold"]),
    ("Weekend Duffle", "bags", 11200, 27400, "images/categories/bags.jpg", None, None, 7, "", False, []),
    ("Chain Shoulder Bag", "bags", 7200, 17600, "images/products/luki-bag.jpg", 8500, None, 10, "", False, ["Gold", "Silver"]),
    ("Belt Bag", "bags", 2900, 7100, "images/products/bag-k.jpg", None, None, 18, "", False, []),
    ("Shopper Tote", "bags", 6400, 15600, "images/categories/bags.jpg", None, None, 11, "", False, ["Tan", "Black"]),
    ("Box Bag", "bags", 8100, 19800, "images/products/crocs-bag.jpg", None, None, 6, "new", False, []),
    ("Phone Pouch", "bags", 1800, 4400, "images/products/bag-k.jpg", 2200, None, 24, "sale", False, []),
    ("Travel Cosmetic Case", "bags", 2600, 6400, "images/categories/bags.jpg", None, None, 20, "", False, []),
    # Beauty
    ("Matte Lip Kit", "beauty", 1600, 3900, "images/products/lipstick.jpg", 2000, None, 22, "", False, []),
    ("Nude Gloss Trio", "beauty", 1800, 4400, "images/products/lipgloss-set.jpg", None, None, 18, "new", False, []),
    ("Setting Spray", "beauty", 1400, 3400, "images/products/mouth-spray.jpg", None, None, 20, "", False, []),
    ("Brow Pencil Duo", "beauty", 900, 2200, "images/categories/beauty.jpg", 1200, None, 30, "sale", False, []),
    ("Compact Powder", "beauty", 1500, 3700, "images/categories/beauty.jpg", None, None, 16, "", False, []),
    ("Makeup Sponge Set", "beauty", 700, 1700, "images/categories/beauty.jpg", 950, None, 40, "sale", False, []),
    ("Eyelash Curler", "beauty", 650, 1600, "images/categories/beauty.jpg", None, None, 25, "", False, []),
    ("Makeup Brush Set 12pcs", "beauty", 3200, 7800, "images/categories/beauty.jpg", 4000, None, 12, "", False, []),
    ("Highlighter Stick", "beauty", 1100, 2700, "images/products/lip-gel.jpg", None, None, 20, "", False, []),
    ("Tinted Lip Oil", "beauty", 950, 2300, "images/products/lip-gel.jpg", 1200, None, 26, "sale", False, []),
    ("False Lashes Pack", "beauty", 800, 1950, "images/categories/beauty.jpg", None, None, 28, "", False, []),
    ("Makeup Remover Wipes", "beauty", 750, 1850, "images/products/wipes.jpg", None, None, 35, "", False, []),
    # Skincare
    ("Vitamin C Serum", "skincare", 2800, 6800, "images/categories/beauty.jpg", 3500, None, 18, "bestseller", False, []),
    ("Hydrating Face Cream", "skincare", 2400, 5900, "images/categories/beauty.jpg", None, None, 16, "", False, []),
    ("Gentle Foam Cleanser", "skincare", 1600, 3900, "images/categories/beauty.jpg", None, None, 22, "", False, []),
    ("Sunscreen SPF50", "skincare", 2200, 5400, "images/categories/beauty.jpg", None, None, 20, "new", False, []),
    ("Clay Mask Jar", "skincare", 1300, 3200, "images/products/acne-mask.jpg", 1700, None, 24, "sale", False, []),
    ("Rose Water Toner", "skincare", 1500, 3700, "images/categories/beauty.jpg", None, None, 18, "", False, []),
    ("Eye Cream", "skincare", 2100, 5100, "images/categories/beauty.jpg", None, None, 14, "", False, []),
    ("Sheet Mask Box 10", "skincare", 1800, 4400, "images/products/acne-mask.jpg", 2300, None, 20, "sale", False, []),
    ("Body Butter", "skincare", 1900, 4600, "images/categories/beauty.jpg", None, None, 18, "", False, []),
    ("Lip Sleeping Mask", "skincare", 850, 2100, "images/products/lip-scrub.jpg", None, None, 26, "", False, []),
    # Hair
    ("Satin Bonnet", "hair-care", 1400, 3400, "images/categories/beauty.jpg", None, None, 22, "", False, ["Black", "Champagne"]),
    ("Wide-Tooth Comb", "hair-care", 500, 1200, "images/categories/beauty.jpg", None, None, 40, "", False, []),
    ("Hair Oil 100ml", "hair-care", 1600, 3900, "images/categories/beauty.jpg", 2000, None, 20, "sale", False, []),
    ("Edge Control", "hair-care", 900, 2200, "images/categories/beauty.jpg", None, None, 28, "", False, []),
    ("Silk Pillowcase", "hair-care", 3200, 7800, "images/categories/fashion.jpg", None, None, 12, "", False, ["Ivory", "Blush"]),
    ("Hair Clips Set", "hair-care", 700, 1700, "images/products/scrunchies.jpg", None, None, 30, "", False, []),
    ("Detangling Brush", "hair-care", 1100, 2700, "images/categories/beauty.jpg", None, None, 18, "", False, []),
    ("Leave-in Conditioner", "hair-care", 1800, 4400, "images/categories/beauty.jpg", None, None, 16, "", False, []),
    ("Headband Pack", "hair-care", 850, 2100, "images/products/scrunchies.jpg", None, None, 24, "", False, []),
    # Nails
    ("Gel Polish Set 6", "nails", 2400, 5900, "images/categories/beauty.jpg", 3000, None, 14, "sale", False, []),
    ("Press-on Nails Kit", "nails", 1600, 3900, "images/categories/beauty.jpg", None, None, 22, "new", False, []),
    ("Nail Lamp", "nails", 4200, 10300, "images/categories/gadgets.jpg", None, None, 8, "", False, []),
    ("Manicure Set", "nails", 1800, 4400, "images/categories/beauty.jpg", None, None, 16, "", False, []),
    ("Cuticle Oil", "nails", 700, 1700, "images/categories/beauty.jpg", None, None, 30, "", False, []),
    ("Nail Stickers Pack", "nails", 450, 1100, "images/categories/beauty.jpg", 650, None, 40, "sale", False, []),
    ("Acrylic Powder Kit", "nails", 3500, 8600, "images/categories/beauty.jpg", None, None, 10, "", False, []),
    ("Nail File Buffer Set", "nails", 550, 1350, "images/categories/beauty.jpg", None, None, 35, "", False, []),
    # Clothing
    ("Oversized Cotton Tee", "clothing", 2800, 6800, "images/categories/fashion.jpg", None, None, 20, "", False, ["Ivory", "Black", "Cocoa"]),
    ("Linen Shirt", "clothing", 4600, 11200, "images/categories/fashion.jpg", None, None, 12, "new", False, ["Cream", "Olive"]),
    ("Palazzo Trousers", "clothing", 5200, 12700, "images/categories/fashion.jpg", 6000, None, 10, "sale", False, ["Black", "Tan"]),
    ("Knit Cardigan", "clothing", 6100, 14900, "images/categories/fashion.jpg", None, None, 9, "", False, ["Camel", "Ivory"]),
    ("Bodycon Midi Dress", "clothing", 7200, 17600, "images/categories/fashion.jpg", None, None, 8, "", False, ["Black", "Wine"]),
    ("Cargo Shorts", "clothing", 3400, 8300, "images/categories/fashion.jpg", None, None, 14, "", False, []),
    ("Satin Slip Skirt", "clothing", 4800, 11700, "images/categories/fashion.jpg", None, None, 11, "", False, ["Champagne", "Black"]),
    ("Polo Shirt", "clothing", 3000, 7300, "images/categories/fashion.jpg", None, None, 16, "", False, ["White", "Navy"]),
    ("Wide-Leg Jeans", "clothing", 6800, 16600, "images/categories/fashion.jpg", None, None, 10, "", False, []),
    ("Cropped Blazer", "clothing", 8900, 21800, "images/categories/fashion.jpg", None, None, 7, "new", False, ["Ivory", "Black"]),
    ("Lounge Set", "clothing", 7500, 18400, "images/categories/fashion.jpg", 8800, None, 9, "sale", False, ["Grey", "Cream"]),
    ("Tank Top 3-Pack", "clothing", 2600, 6400, "images/categories/fashion.jpg", None, None, 20, "", False, []),
    # Ankara
    ("Ankara Midi Dress", "ankara", 8500, 20800, "images/categories/fashion.jpg", None, None, 8, "bestseller", True, []),
    ("Ankara 2-Piece Set", "ankara", 9800, 24000, "images/categories/fashion.jpg", None, None, 7, "", True, []),
    ("Ankara Wrap Gown", "ankara", 11200, 27400, "images/categories/fashion.jpg", None, None, 6, "new", False, []),
    ("Ankara Shirt Dress", "ankara", 7600, 18600, "images/categories/fashion.jpg", 8900, None, 9, "sale", False, []),
    ("Ankara Wide Palazzos", "ankara", 6400, 15600, "images/categories/fashion.jpg", None, None, 10, "", False, []),
    ("Ankara Bomber Jacket", "ankara", 9200, 22500, "images/categories/fashion.jpg", None, None, 6, "", False, []),
    ("Ankara Headwrap", "ankara", 1800, 4400, "images/categories/fashion.jpg", None, None, 22, "", False, []),
    ("Ankara Kimono", "ankara", 7000, 17100, "images/categories/fashion.jpg", None, None, 8, "", False, []),
    ("Ankara Jumpsuit", "ankara", 10500, 25700, "images/categories/fashion.jpg", None, None, 5, "", False, []),
    ("Ankara Pencil Skirt", "ankara", 4800, 11700, "images/categories/fashion.jpg", None, None, 12, "", False, []),
    ("Ankara Men's Shirt", "ankara", 5600, 13700, "images/categories/fashion.jpg", None, None, 10, "", False, []),
    ("Ankara Maxi Gown", "ankara", 12800, 31300, "images/categories/fashion.jpg", None, None, 5, "new", False, []),
    # Shoes
    ("Nude Court Heels", "shoes", 9800, 24000, "images/products/heels.jpg", None, None, 7, "", False, ["Nude", "Black"]),
    ("Gold Evening Heels", "shoes", 11200, 27400, "images/categories/shoes.jpg", None, None, 6, "new", False, []),
    ("Leather Loafers", "shoes", 8600, 21000, "images/categories/shoes.jpg", None, None, 9, "", False, ["Tan", "Black"]),
    ("Slide Sandals", "shoes", 4200, 10300, "images/categories/shoes.jpg", 5000, None, 14, "sale", False, []),
    ("Chunky Sneakers", "shoes", 7800, 19100, "images/categories/shoes.jpg", None, None, 10, "", False, ["White", "Cream"]),
    ("Ankle Boots", "shoes", 10400, 25500, "images/categories/shoes.jpg", None, None, 6, "", False, []),
    ("Flat Ballet Pumps", "shoes", 4600, 11200, "images/categories/shoes.jpg", None, None, 12, "", False, ["Black", "Nude"]),
    ("Platform Sandals", "shoes", 6900, 16900, "images/products/heels.jpg", None, None, 8, "", False, []),
    ("Men's Derby Shoes", "shoes", 9800, 24000, "images/categories/shoes.jpg", None, None, 7, "", False, []),
    ("Espadrille Slides", "shoes", 3800, 9300, "images/categories/shoes.jpg", None, None, 16, "", False, []),
    # Accessories
    ("Pearl Drop Earrings", "accessories", 1600, 3900, "images/categories/gadgets.jpg", None, None, 20, "", False, []),
    ("Layered Gold Necklace", "accessories", 2200, 5400, "images/products/tomi-watch.jpg", None, None, 14, "new", False, []),
    ("Leather Belt", "accessories", 2400, 5900, "images/products/key-holder.jpg", None, None, 16, "", False, ["Tan", "Black"]),
    ("Silk Scarf", "accessories", 2800, 6800, "images/categories/fashion.jpg", 3400, None, 12, "sale", False, []),
    ("Classic Sunglasses", "accessories", 3200, 7800, "images/categories/gadgets.jpg", None, None, 14, "", False, []),
    ("Cuff Bracelet", "accessories", 1800, 4400, "images/products/tomi-watch.jpg", None, None, 18, "", False, []),
    ("Beaded Waist Chain", "accessories", 1500, 3700, "images/categories/fashion.jpg", None, None, 20, "", False, []),
    ("Card Holder", "accessories", 1200, 2900, "images/products/key-holder.jpg", None, None, 24, "", False, []),
    ("Hair Pin Set", "accessories", 800, 1950, "images/products/scrunchies.jpg", None, None, 30, "", False, []),
    ("Statement Ring", "accessories", 1100, 2700, "images/categories/gadgets.jpg", None, None, 18, "", False, []),
    # Gadgets
    ("Wireless Neckband", "gadgets", 3400, 8300, "images/products/earpod.jpg", 4200, None, 14, "sale", False, []),
    ("Power Bank 20000mAh", "gadgets", 6800, 16600, "images/categories/gadgets.jpg", None, None, 12, "", False, []),
    ("LED Ring Light", "gadgets", 5400, 13200, "images/products/tripod.jpg", None, None, 9, "", False, []),
    ("Bluetooth Speaker", "gadgets", 4900, 12000, "images/categories/gadgets.jpg", 5800, None, 11, "sale", False, []),
    ("Phone Stand", "gadgets", 1200, 2900, "images/products/vacuum-holder.jpg", None, None, 28, "", False, []),
    ("Type-C Cable 2m", "gadgets", 800, 1950, "images/categories/gadgets.jpg", None, None, 40, "", False, []),
    ("Wireless Mouse", "gadgets", 2600, 6400, "images/categories/gadgets.jpg", None, None, 16, "", False, []),
    ("Smart Watch Band", "gadgets", 1400, 3400, "images/products/tomi-watch.jpg", None, None, 22, "", False, []),
    ("Mini Projector", "gadgets", 18500, 45300, "images/categories/gadgets.jpg", None, None, 4, "new", False, []),
    ("F15 Wireless Mic — Double", "gadgets", 7400, 18000, "images/products/f15-mic.jpg", 9500, None, 0, "sale", False, []),
    ("Desk Lamp USB", "gadgets", 3100, 7600, "images/categories/gadgets.jpg", None, None, 12, "", False, []),
    ("Car Phone Mount", "gadgets", 1600, 3900, "images/products/vacuum-holder.jpg", 2100, None, 20, "sale", False, []),
    # Household
    ("Insulated Travel Mug", "household", 4350, 10500, "images/products/stanley.jpg", None, None, 14, "", False, []),
    ("Laundry Basket", "household", 3200, 7800, "images/categories/household.jpg", None, None, 12, "", False, []),
    ("Spice Rack", "household", 2800, 6800, "images/categories/household.jpg", None, None, 10, "", False, []),
    ("Non-stick Frying Pan", "household", 4500, 11000, "images/products/alum-pot.jpg", 5400, None, 11, "sale", False, []),
    ("Water Dispenser Tap", "household", 1900, 4600, "images/categories/household.jpg", None, None, 16, "", False, []),
    ("Bed Sheet Set", "household", 6200, 15200, "images/categories/household.jpg", None, None, 9, "", False, ["Ivory", "Grey"]),
    ("Bath Towel Pair", "household", 3400, 8300, "images/categories/household.jpg", None, None, 18, "", False, []),
    ("Trash Bin Pedal", "household", 2700, 6600, "images/categories/household.jpg", None, None, 14, "", False, []),
    ("Chopping Board Set", "household", 2100, 5100, "images/categories/household.jpg", None, None, 16, "", False, []),
    ("Electric Kettle", "household", 5800, 14200, "images/categories/household.jpg", None, None, 10, "", False, []),
    ("Hand Mixer", "household", 6400, 15600, "images/categories/gadgets.jpg", None, None, 8, "", False, []),
    ("Storage Boxes 3pcs", "household", 3600, 8800, "images/products/storage-bag.jpg", None, None, 14, "", False, []),
    ("Door Mat", "household", 1600, 3900, "images/categories/household.jpg", None, None, 20, "", False, []),
    ("Clothes Hangers 20pcs", "household", 2400, 5900, "images/products/hanger.jpg", None, None, 18, "", False, []),
    ("Table Cloth", "household", 2200, 5400, "images/categories/household.jpg", None, None, 14, "", False, []),
    ("Vacuum Flask 1L", "household", 3900, 9500, "images/products/stanley.jpg", 4700, None, 12, "sale", False, []),
    # Decor
    ("Gold Candle Holders Pair", "decor", 2800, 6800, "images/categories/household.jpg", None, None, 12, "", False, []),
    ("Ceramic Vase", "decor", 3400, 8300, "images/categories/household.jpg", None, None, 10, "", False, []),
    ("Wall Mirror Round", "decor", 7200, 17600, "images/products/mini-mirror.jpg", None, None, 6, "", False, []),
    ("Scented Candle Trio", "decor", 2400, 5900, "images/products/mini-diffuser.jpg", None, None, 16, "", False, []),
    ("Photo Frame Set", "decor", 1800, 4400, "images/categories/household.jpg", None, None, 14, "", False, []),
    ("Faux Plant in Pot", "decor", 2600, 6400, "images/categories/household.jpg", None, None, 12, "", False, []),
    ("Throw Pillow Pair", "decor", 3200, 7800, "images/categories/household.jpg", None, None, 14, "", False, ["Cream", "Gold"]),
    ("Table Runner", "decor", 1600, 3900, "images/categories/household.jpg", None, None, 18, "", False, []),
    ("LED String Lights", "decor", 1400, 3400, "images/products/glow.jpg", None, None, 22, "", False, []),
    ("Abstract Sculpture", "decor", 4800, 11700, "images/categories/household.jpg", None, None, 6, "new", False, []),
    # Gift sets
    ("Men 7-in-1 Gift Set", "gift-set", 14500, 35500, "images/categories/gadgets.jpg", None, None, 6, "bestseller", True, [],
     "Seven-piece men's gift set. Watch, grooming and accessories in one box."),
    ("Her Evening Box", "gift-set", 12800, 31300, "images/categories/beauty.jpg", None, None, 7, "", False, []),
    ("Couples Hamper", "gift-set", 18600, 45500, "images/categories/household.jpg", None, None, 4, "new", False, []),
    ("Spa Night Set", "gift-set", 7600, 18600, "images/categories/beauty.jpg", 8900, None, 10, "sale", False, []),
    ("Grooming Starter Kit", "gift-set", 5400, 13200, "images/products/beard-balm.jpg", None, None, 12, "", False, []),
    ("Hostess Gift Box", "gift-set", 9800, 24000, "images/products/gold-cutlery.jpg", None, None, 6, "", False, []),
    ("New Mum Basket", "gift-set", 11200, 27400, "images/categories/household.jpg", None, None, 5, "", False, []),
    ("Teen Glow Kit", "gift-set", 6200, 15200, "images/categories/beauty.jpg", None, None, 10, "", False, []),
    # Children
    ("Kids Water Bottle", "children", 1200, 2900, "images/products/bottle.jpg", None, None, 20, "", False, ["Pink", "Blue"]),
    ("Children Slippers", "children", 1600, 3900, "images/categories/shoes.jpg", None, None, 16, "", False, []),
    ("Kids Backpack", "children", 2800, 6800, "images/categories/bags.jpg", None, None, 12, "", False, []),
    ("Soft Plush Toy", "children", 1800, 4400, "images/categories/fashion.jpg", None, None, 14, "", False, []),
    ("Kids Lunch Box", "children", 1500, 3700, "images/categories/household.jpg", None, None, 18, "", False, []),
    ("Baby Blanket", "children", 2400, 5900, "images/categories/household.jpg", None, None, 10, "", False, []),
    ("Children Sunglasses", "children", 900, 2200, "images/categories/gadgets.jpg", None, None, 22, "", False, []),
    ("Kids Hair Clips", "children", 600, 1470, "images/products/scrunchies.jpg", None, None, 28, "", False, []),
    ("Story Time Lamp", "children", 3200, 7800, "images/products/glow.jpg", None, None, 8, "new", False, []),
    ("School Stationery Set", "children", 1400, 3400, "images/categories/household.jpg", None, None, 20, "", False, []),
    # Packaging
    ("Gift Box Medium", "packaging", 800, 1950, "images/categories/household.jpg", None, None, 40, "", False, []),
    ("Gift Box Large", "packaging", 1200, 2900, "images/categories/household.jpg", None, None, 28, "", False, []),
    ("Organza Bags 20pcs", "packaging", 900, 2200, "images/categories/household.jpg", None, None, 30, "", False, []),
    ("Tissue Paper Pack", "packaging", 600, 1470, "images/categories/household.jpg", None, None, 40, "", False, []),
    ("Branded Carry Bag", "packaging", 450, 1100, "images/categories/bags.jpg", None, None, 50, "", False, []),
    ("Ribbon Roll", "packaging", 500, 1225, "images/categories/household.jpg", None, None, 35, "", False, []),
    ("Thank You Cards 50", "packaging", 700, 1700, "images/categories/household.jpg", None, None, 24, "", False, []),
    ("Mailer Boxes 10", "packaging", 1800, 4400, "images/categories/household.jpg", None, None, 16, "", False, []),
    ("Sticker Seal Pack", "packaging", 400, 980, "images/categories/household.jpg", None, None, 45, "", False, []),
    ("Wine Gift Sleeve", "packaging", 650, 1600, "images/categories/household.jpg", None, None, 22, "", False, []),
]

for item in extras:
    if len(item) == 11:
        products.append(P(n, *item))
    else:
        products.append(P(n, *item))
    n += 1

assert len(products) >= 200, len(products)

out = Path(__file__).with_name("seed.json")
out.write_text(json.dumps(products, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"Wrote {len(products)} products → {out}")
