"""Shared pytest fixtures.

The suite writes to a single /tmp catalogue file. Confirming an order now
decrements product.stock, so a leftover edit to a seed (wix-*) row would
poison later tests such as test_over_order_rejected_with_counts (expects 24).
Restore seed stock after every test without weakening any assertion.

TRACKED-FILE GUARD. CATALOG_PATH=/tmp is not by itself enough to keep the
repository clean: `repo_sync.regenerate()` writes `REPO_ROOT/data/catalog.json`
and `REPO_ROOT/js/products-data.js`, and REPO_ROOT defaults to the real
checkout. `test_admin_product_delete_ok_when_supabase_confirms` sets
`Config.ENV = "production"`, which used to lift `catalog._sync_repo_async`'s
testing guard and fire a real `regenerate(commit=True, push=True)` in a daemon
thread - so a single test rewrote the tracked catalogue mid-suite and the CI
harness committed the artefacts.

Two layers now prevent that:

  * catalog._sync_repo_async refuses to run whenever pytest is the runner,
    regardless of Config.ENV (a test is allowed to fake production); and
  * `_tracked_repo_is_read_only` below points repo_sync at a scratch tree,
    neutralises its git calls, and fails the test if a tracked file changed.
"""
import hashlib
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
os.environ.setdefault("DB_PATH", "/tmp/jaura_test.db")
os.environ.setdefault("CATALOG_PATH", "/tmp/jaura_test_catalog.json")
os.environ.setdefault("FLASK_ENV", "testing")
os.environ.setdefault("SECRET_KEY", "test-secret-key")
os.environ.setdefault("ADMIN_EMAILS", "jaurastore@gmail.com")
os.environ.setdefault("MAIL_MODE", "none")
# The admin category editor writes to CATEGORIES_PATH, which api.py resolves at
# IMPORT time - so it has to be redirected here, before any test module imports
# app/api, or a test that saves categories rewrites the tracked
# data/categories.json (it wiped all 11 real categories the first time).
_SCRATCH_CATEGORIES = "/tmp/jaura_test_categories.json"
os.environ.setdefault("CATEGORIES_PATH", _SCRATCH_CATEGORIES)
if not os.path.exists(_SCRATCH_CATEGORIES):
    import shutil
    shutil.copyfile(os.path.join(ROOT, "data", "categories.json"),
                    _SCRATCH_CATEGORIES)

# Same problem, worse consequence, for the site-settings file. Every test
# module calls os.environ.setdefault("SITE_CONFIG_PATH", <its own file>), so
# whichever module is COLLECTED FIRST wins for the whole session - adding a new
# test file silently changes which file every other module reads and writes.
# The file also outlives the process, so a value written by an earlier run
# leaked into the next one. Pin one path here and start it empty.
_SCRATCH_SITE = "/tmp/jaura_test_site.json"
os.environ["SITE_CONFIG_PATH"] = _SCRATCH_SITE
try:
    os.remove(_SCRATCH_SITE)
except OSError:
    pass

import pytest  # noqa: E402

# Repository files a test must never rewrite. data/seed.json is the immutable
# Wix import source; the other two are regenerated by repo_sync.
TRACKED_DATA_FILES = ("data/catalog.json", "data/seed.json",
                      "data/categories.json", "js/products-data.js")


def _digest(path):
    try:
        with open(path, "rb") as fh:
            return hashlib.sha256(fh.read()).hexdigest()
    except OSError:
        return ""


@pytest.fixture(scope="session")
def scratch_repo_root(tmp_path_factory):
    """A throwaway REPO_ROOT so repo_sync can never reach the real checkout."""
    return str(tmp_path_factory.mktemp("repo-sync-scratch"))


@pytest.fixture(autouse=True)
def _tracked_repo_is_read_only(monkeypatch, scratch_repo_root):
    """Fail the test if it rewrote a tracked repository file.

    This is the assertion behind "git status stays clean after pytest": rather
    than trusting every test to remember a scratch path, verify the outcome.
    """
    try:
        import repo_sync
        monkeypatch.setattr(repo_sync, "REPO_ROOT", scratch_repo_root)
        # A test may still ask repo_sync to commit/push; make both no-ops so a
        # stray call cannot produce a commit or a network push.
        monkeypatch.setattr(repo_sync, "_commit_and_push",
                            lambda **kw: (True, {"skipped": "pytest"}))
        monkeypatch.setattr(repo_sync, "_push_via_api",
                            lambda *a, **k: (False, {"skipped": "pytest"}))
    except Exception:                       # pragma: no cover - import safety
        pass

    before = {rel: _digest(os.path.join(ROOT, rel)) for rel in TRACKED_DATA_FILES}
    yield
    changed = [rel for rel in TRACKED_DATA_FILES
               if _digest(os.path.join(ROOT, rel)) != before[rel]]
    assert not changed, (
        "pytest mutated tracked repository file(s): " + ", ".join(changed) +
        ". Tests must write through CATALOG_PATH and a scratch REPO_ROOT, "
        "never the real checkout.")


@pytest.fixture(autouse=True)
def _restore_seed_stock():
    yield
    try:
        import catalog as catalog_mod
        seed = {str(p.get("id")): p for p in catalog_mod._seed_products()}
        data, path = catalog_mod._load_overrides()
        products = data.get("products") or []
        changed = False
        for p in products:
            src = seed.get(str(p.get("id") or ""))
            if not src:
                continue
            if p.get("stock") != src.get("stock") or p.get("optionStock") != src.get("optionStock"):
                p["stock"] = src.get("stock")
                if "optionStock" in src:
                    p["optionStock"] = src.get("optionStock")
                elif "optionStock" in p:
                    p.pop("optionStock", None)
                changed = True
        if changed:
            catalog_mod._write_overrides(data, path)
    except Exception:
        pass
