#!/usr/bin/env python3
"""Read-only publication audit: bucket product rows under publication.decide.

Never touches Supabase, never writes a file unless --out is given. Input is
either a catalogue JSON (``{"products": [...]}`` or a bare list) saved from
``GET /api/catalog?all=1`` (admin session) / a table export, or ``--seed`` for
the shipped ``data/seed.json``.

    python3 tools/publication_audit.py catalog.json
    python3 tools/publication_audit.py --seed --exclude-ids catalog.json
    python3 tools/publication_audit.py catalog.json --sql > proposal.sql

``--sql`` prints ONLY the section-0 allowlist + section-1 SELECT preview for
the given rows, in the layout of docs/publication-online-flags-*.sql. It never
prints an UPDATE.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import publication  # noqa: E402


def _load(path):
    with open(path, encoding="utf-8") as fh:
        data = json.load(fh)
    if isinstance(data, dict):
        data = data.get("products") or []
    return [p for p in data if isinstance(p, dict) and p.get("id")]


def _ids(rows):
    return {str(p.get("id")) for p in rows}


def report(rows, title):
    buckets = publication.classify(rows)
    print(f"# {title}: {len(rows)} rows")
    for b in publication.BUCKETS:
        print(f"  {b:17s} {len(buckets[b])}")
    print()
    for b in publication.BUCKETS:
        if not buckets[b]:
            continue
        print(f"## {b} ({len(buckets[b])})")
        for d in buckets[b]:
            why = "; ".join(d["reasons"]) or "-"
            print(f"  {d['id']:16s} img={d['image_status']:11s} ngn={d['priceNgn']!r:>8} "
                  f"cfa={d['priceCfa']!r:>8} stock={d['stock_quantity']!r:>5}  {why}")
        print()
    return buckets


def sql_preview(buckets):
    live = [d["id"] for d in buckets["live"]]
    off = [(d["id"], d["bucket"]) for b in publication.BUCKETS if b != "live" for d in buckets[b]]
    print("-- section 0: allowlists (generated by tools/publication_audit.py; SELECT only)")
    print(f"-- online=true  ({len(live)}): " + ", ".join(live))
    print(f"-- online=false ({len(off)}): " + ", ".join(i for i, _ in off))
    print("with allowlist(id, target_online, bucket) as (\n  values")
    vals = [f"    ('{i}', true,  'live')" for i in live]
    vals += [f"    ('{i}', false, '{b}')" for i, b in off]
    print(",\n".join(vals))
    print(""")
select a.bucket, a.id, p.name, p.online as online_now, a.target_online as online_after,
       (p.online is distinct from a.target_online) as will_change,
       p."priceNgn", p."priceCfa", p.stock_quantity, p.image_url, p.updated_at,
       (p.id is null) as missing_in_table
from allowlist a left join public.products p on p.id = a.id
order by a.bucket, a.id;""")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("catalog", nargs="?", help="catalogue JSON to audit")
    ap.add_argument("--seed", action="store_true", help="audit data/seed.json instead")
    ap.add_argument("--exclude-ids", metavar="JSON", help="drop ids present in this catalogue JSON (e.g. rows already in Supabase)")
    ap.add_argument("--sql", action="store_true", help="print the allowlist + SELECT preview (never an UPDATE)")
    ap.add_argument("--out", help="write the bucket JSON here (optional)")
    a = ap.parse_args(argv)

    if a.seed:
        rows = _load(os.path.join(ROOT, "data", "seed.json"))
        title = "data/seed.json"
    elif a.catalog:
        rows = _load(a.catalog)
        title = a.catalog
    else:
        ap.error("give a catalogue JSON or --seed")
    if a.exclude_ids:
        drop = _ids(_load(a.exclude_ids))
        rows = [p for p in rows if str(p.get("id")) not in drop]
        title += f" minus {len(drop)} ids from {a.exclude_ids}"

    if a.sql:
        sql_preview(publication.classify(rows))
        return 0
    buckets = report(rows, title)
    if a.out:
        with open(a.out, "w", encoding="utf-8") as fh:
            json.dump({b: [d["id"] for d in buckets[b]] for b in publication.BUCKETS}, fh, indent=2)
        print(f"wrote {a.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
